# Generated by Django 4.0.1 on 2022-02-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportal.jobtype'),
        ),
    ]
