# Generated by Django 4.0.1 on 2022-02-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_alter_profile_github_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='type',
            new_name='types',
        ),
    ]
